#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x

# Since we only use python to train a model for evaluation test, it is sufficient to train the model only with one python version.
# Now it is trained with Python 2.7. If it is not supported anymore, need to use another python version.
PythonVer=$(python -c "import sys; print(sys.version_info[0])")
if [ "$PythonVer" == "3" ]; then
  echo Skip this test for Python 3.4/3.5. Run this test only on Python 2.7 to save test time. 
  exit 0
fi

# Train resnet cifar model and atis model
python train_models_for_evaluation.py || exit $?

cp $TEST_ROOT_DIR/../../Examples/LanguageUnderstanding/ATIS/BrainScript/query.wl . || exit $?
cp $TEST_ROOT_DIR/../../Examples/LanguageUnderstanding/ATIS/BrainScript/slots.wl . || exit $?

# Set CUDA_VISIBLE_DEVICES to exclude all gpu if running on cpu device
if [ "$TEST_DEVICE" == "cpu" ]; then
  export CUDA_VISIBLE_DEVICES=-1
fi

if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/CNTKLibraryCSEvalExamplesTest.exe
else
  echo Cannot run CNTKLibraryCSEvalExampleTest on Linux.
  exit 1
fi

ExitCode=$?

if [ "$TEST_DEVICE" == "cpu" ]; then
  unset CUDA_VISIBLE_DEVICES
fi

exit $ExitCode
